### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by exercitus** [adolfintel/OpenPods#1]
Connection: Shows battery level on any local set of airpods. Regardless if they have ever been connected to phone or not. 

Icon shows up constantly even when not near airpods.

The icon image looks folded when it's on the lockscreen due to the image being too tall.

Verizon Note 9 on Android 9.0

**Comment by adolfintel** [comment]
>Connection: Shows battery level on any local set of airpods. Regardless if they have ever been connected to phone or not.

It's an android limitation. I'll write an article about it soon. Basically it can only lock on to the strongest signal coming from a set of airpods.

>Icon shows up constantly even when not near airpods.

The icon should go away when you disconnect your airpods, not sure what's going on here. How can I replicate this problem?

>The icon image looks folded when it's on the lockscreen due to the image being too tall.

Cannot replicate. Can you show me a screenshot?

**Comment by RawSlugs** [comment]
> The icon image looks folded when it's on the lockscreen due to the image being too tall.

> Cannot replicate. Can you show me a screenshot?

@adolfintel
Everything in the app works great! But the notification icon is massive for me https://i.imgur.com/KgVxpNf.png

**Comment by adolfintel** [comment]
That's a big ass icon. I have no idea why it looks normal on my phone.
I'll see if I can find something, otherwise I'll just get rid of it, it's not like it's necessary.

**Comment by adolfintel** [comment]
@RawSlugs fixed it
