### ISSUE TITLE
[Question] Why does the Bluetooth LE scan apply a filter with a mask containing "-1"?

### ISSUE THREAD

**Issue by andrewtran1995** [adolfintel/OpenPods#104]
## Question
I notice that when creating the scan filter for the Bluetooth LE scan to sniff out AirPods, the code sets the manufacturer data mask to `-1` for indices `0` and `1`.
https://github.com/adolfintel/OpenPods/blob/7d8d286350dea24a50674d53ff61d5d85d320651/OpenPods/app/src/main/java/com/dosse/airpods/PodsService.java#L198
I'm a little confused how that works properly, given Android's documentation that the mask should essentially [consist of booleans](https://developer.android.com/reference/android/bluetooth/le/ScanFilter.Builder#setManufacturerData(int,%20byte[],%20byte[])) to determine if the mask is applied in that position or not. Would it be possible to get an explanation for how this works? Thanks in advance!

## Context
For context, I'm trying to build my own AirPod battery app (giving full credit of the battery information derivation to this repo): [andrewtran1995/airpod-battery](https://github.com/andrewtran1995/airpod-battery).
* **Where I'm at now**: I've gotten to the point where I can launch my app successfully, but am having difficulty finding a scan result for my AirPod Pros, even without a `ScanFilter` enabled; no `ScanResult` returns with manufacturer-specific data of length `27`.
* **In terms of licensing and fair-use**: I'm hoping to take this app to completion, but do not intend to profit off of it in any way (it's being done partially as a design project for my girlfriend's UI/UX bootcamp). It could be cool to distribute it on the Play Store (as an entirely free app) with due credit given to OpenPods.

If it is more appropriate to take any of the above offline, please let me know. Thank you for the work you've done thus far, and providing your findings in this open source format! ❤️

**Comment by adolfintel** [comment]
I don't remember why I used -1 insted of specifying the mask bit by bit, but a value of -1 in binary means that all bits are set to 1.

You are free (and encouraged) to use OpenPods to make other open source apps :)
