### ISSUE TITLE
don't seems to work ?

### ISSUE THREAD

**Issue by kiuKisas** [adolfintel/OpenPods#110]
I download your app from f-droid, earpod connected, launched the app, add autorisations, and.. nothing in notification center..
I try to disconnect and reconnect the earpod and.. nothing.. :(|

huawai p smart 2019
android 10
EMUI 10.0.0.260

**Comment by adolfintel** [comment]
It's a problem with EMUI unfortunately, we are aware of it and we've added a warning some time ago
