### ISSUE TITLE
EMUI10 

### ISSUE THREAD

**Issue by palachuter** [adolfintel/OpenPods#111]
Hello, someone have an idea for how to use the app with EMUI 10 on a Huawei Mate 20 lite ? This one is not working actually on my phone, i saw something like Huawei have some strange bluetooth antenna or something like that...
Thanks you :)
Palachuter.
( btw i used the v1.5)

**Comment by adolfintel** [comment]
It's a problem with EMUI, we're aware of this and we've already added a warning

**Comment by palachuter** [comment]
Hi,
Thanks for your quickly reply,
So i guess there is no patch no anything like that ?
