### ISSUE TITLE
Missing notification from version 1.4

### ISSUE THREAD

**Issue by fvasco** [adolfintel/OpenPods#114]
On my Mi A2 Lite with Android 10, the notification was shown until version 1.3, both version 1.4 and 1.5 does not detect my Airpod first generation, even starting the app.

**Comment by adolfintel** [comment]
If I had to guess it's the target SDK of 29, which was changed in 1.4 triggering some bug in your rom.
Do you have android studio installed?

**Comment by fvasco** [comment]
I Federico,
I am a Java/Kotlin developer and I developed a [toy app](https://fvasco.github.io/pinpoi/), please send me your instructions.

Funny fact: I lost my earphones, but I will test it as soon as possible :)

**Comment by adolfintel** [comment]
Great.
Please download the current master, check if the problem still occurs, and if it does, try changing the SDK version (1.3 used SDK 23).

**Comment by froachy** [comment]
@adolfintel Experienced this same bug on Pixel 5 on Android 11 and followed your advice to rebuild application, and this successfully brought back the battery status notification.

**Comment by fvasco** [comment]
Versione 1.5.1 works as expected, it is OK for me.

PS: Mi A2 Lite is an Android One device, I detected the issue with LineageOS and this app works on Havoc 4.4+GApps.
