### ISSUE TITLE
Not detecting AirpodsPro on Pixel 5

### ISSUE THREAD

**Issue by catskul** [adolfintel/OpenPods#117]
Installed app, connected to working AirpodsPro, and is apparently not detected by the app.

OS: Android 11
App: OpenPods 1.5
HW: Pixel 5

**Comment by adolfintel** [comment]
Probably related to #106 .
Can you test the current master and report back? I can send you an APK if you want.

**Comment by catskul** [comment]
Would be happy to test. APK would be much appreciated.

**Comment by adolfintel** [comment]
Here it is: 
[app-release.zip](https://github.com/adolfintel/OpenPods/files/6207889/app-release.zip)

**Comment by catskul** [comment]
Works!

**Comment by Electric1447** [comment]
We should probably release a new version of the app...

**Comment by adolfintel** [comment]
> We should probably release a new version of the app...

Yeah, I'll do it now

**Comment by catskul** [comment]
I should mention that I uninstalled openpods this morning because I was having performance and battery problems. Hard to be certain but I do believe it was related to openpods
