### ISSUE TITLE
After taking the airpods out from the case the battery percentage drops from 100% to 95%

### ISSUE THREAD

**Issue by dontknowhowtocoding** [adolfintel/OpenPods#118]
![Screenshot_20210402-124920_Discord.jpg](https://user-images.githubusercontent.com/69205883/113409785-5259a300-93b2-11eb-84fd-c0adb2e2ee34.jpg)

![Screenshot_20210402-125013_Discord.jpg](https://user-images.githubusercontent.com/69205883/113409805-58e81a80-93b2-11eb-83a2-25f3b6123689.jpg)

Is that normal or my airpods battery health is bad?

Thank you.

**Comment by adolfintel** [comment]
Both. It's normal that the case has a threshold above which it will stop charging them and just trickle charge them if they fall below a certain threshold. As the batteries degrade, they can hold less and less charge so they'll drop below 100% more quickly if not immediately when you remove them from the case.
