### ISSUE TITLE
[REQUEST] How to build up an environment and contribution guidelines

### ISSUE THREAD

**Issue by acallejp97** [adolfintel/OpenPods#119]
Hi everyone. I just found this project and I love it. I would like to build an environment o n my local, but I have no idea about which technology is been used and how to upload my changes in order to be reviewed by an admin.

Thank you all in advance.

Best regards.

**Comment by adolfintel** [comment]
Like 99% of android apps, this is a java application, you can load the project in android studio, it will automatically download everything it needs and then you're ready to go.

Being a small project, we don't really have contribution guidelines, if you make some changes, send a PR and I'll take a look at it.
