### ISSUE TITLE
[Feature request] Noise canceling toggle ON/OFF

### ISSUE THREAD

**Issue by schweppes-0x** [adolfintel/OpenPods#128]
I've been using the app for more than 3 months now and I'm amazed, great work! I appreciate people contributing usefull things like this. 
My request would be:

Just like Apple's ON/OFF noise canceling button for each earbug. 
You could control whether it's turned on or off. Like left is on and right is off.

**Comment by adolfintel** [comment]
Hi,
It was already suggested in #58, but it requires additional reverse engineering work that no one has done yet.
