### ISSUE TITLE
Hard to see information on dark theme

### ISSUE THREAD

**Issue by RawSlugs** [adolfintel/OpenPods#13]
![Screenshot_20190508-141731](https://user-images.githubusercontent.com/28845508/57374990-89aa7f80-719c-11e9-9b7a-c1b6e9202722.png)

When Android is set to dark theme the icons are black and really hard to see (and the numbers look very grey) can't see notification icon is status bar either..

Disclaimer: I am using Android Q beta. Not sure if it's Android or the app...

**Comment by adolfintel** [comment]
Can you test this APK? I forced the colors to white and black.
[test.zip](https://github.com/adolfintel/OpenPods/files/3178632/test.zip)
