### ISSUE TITLE
Add Support for Nothing Ear (1)

### ISSUE THREAD

**Issue by sebastianha** [adolfintel/OpenPods#130]
Hi,

would it be possible to add support for the Nothing Ear (1) head phones?

Gadgetbridge recently has added support ( https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/2403 ) but I think that headphone support is not the strength of Gadgetbridge and it should be added by an app like this here.

Perhaps you can use the code to add support for these cheap but great headphones.

Regards, Sebastian

**Comment by steam3d** [comment]
This method does not seem to work with AirPods.  The Apple use their own protocol to control AirPods state, battery and firmware update

**Comment by vanous** [comment]
> This method does not seem to work with AirPods. The Apple use their own protocol to control AirPods state, battery and firmware update

We have Nothing Ear (1) in Gadgetbridge, if you are interested in another privacy friendly app.

https://codeberg.org/Freeyourgadget/Gadgetbridge

https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Nothing-Ear-%281%29

**Comment by sebastianha** [comment]
Hi,

it works basically in Gb but it does not show the battery status for each bud and the case. I use Gb for my MiBand which works fine but for Buds I would expect a permanent notification showing the battery status of all parts and quick access to preferences. Gb is more general, that's why I would prefer to have this functionality in this app here.

Regards, Sebastian

**Comment by vanous** [comment]
> it works basically in Gb but it does not show the battery status for each bud and the case.

That is work in progress, which already works, we will add dedicated labels or different icons.

![image](https://user-images.githubusercontent.com/3680926/139684282-81c35dd1-7611-4d3a-8129-280f755bd966.png)

>permanent notification showing the battery status of all parts 

That **would** be possible...

>and quick access to preferences

This **could** be done via a widget, dedicated to headphones.

We accept PRs :) Anyways, this is all unrelated here, but it was interesting for me to learn about OpenPods.

@adolfintel awesome job here on the project! Congrats! And very sorry for the off-topic.

**Comment by sebastianha** [comment]
Hey, that looks awesome! Keep up the great work!
And also sorry for off topic. I will close this ticket for now. Feel free to reopen if there is any plan to support nothing ear here in this app.
