### ISSUE TITLE
Copycat/Clone on Google Play

### ISSUE THREAD

**Issue by Poussinou** [adolfintel/OpenPods#138]
Hi @adolfintel 

Is this a copycat of your app below ?

https://play.google.com/store/apps/details?id=com.mixsoftapps.airdrobattery

I also saw in another Issue you already reported a lot of copycats. Could you please provide the links to this app or, better, to the developer page of this copycats? I would like to see if they have other stolen floss apps that I can report. Thanks in advance.

**Comment by adolfintel** [comment]
Yes but the app contains code that will break functionality if it's published on google play, as you can see from the reviews :laughing:

**Comment by hackerb9** [comment]
I clicked the google play link just to "Flag for Copycat or Impersonation", but started cracking up at the reviews. Normally I'm opposed to software that breaks itself, and even now I'm unsure, but I have to say, it does feel satisfying to see violators of the GNU GPL being thwarted.

**Comment by Poussinou** [comment]
This copycat is now down. I'm closing this Issue.

Please report it here if you find other copycats in the future.
