### ISSUE TITLE
Notification icon very big

### ISSUE THREAD

**Issue by 2xlink** [adolfintel/OpenPods#14]
First of all: Thanks for the application, it is very useful :) 

Secondly, I am not sure why the notification icon is so much larger than other icons on my phone. See here: 
![Untitled2](https://user-images.githubusercontent.com/8763936/57701463-57959380-765c-11e9-9183-778fe5b51ee5.png)

I fixed it by resizing the `notification_icon.png` resource (maybe that could be the wrong approach …):
![Untitled](https://user-images.githubusercontent.com/8763936/57701563-8f044000-765c-11e9-8042-ca1d06f678a6.png)

I can make a pull request if you want :)

Cheers

**Comment by adolfintel** [comment]
Wasn't this fixed like 2 months ago in commit f421e0febf639d6832e38fc9c4093dd6e8671db5 ?

**Comment by 2xlink** [comment]
Well, not on my system at least ;)
I am not entirely sure where the problem could stem from. I use a Samsung Galaxy S7 with the default interface, maybe they fucked something up with notification icon handling. I assume that the icon on your phone is the correct size?

**Comment by nichbar** [comment]
I can confirm that issue still exist on my oneplus 3T which is running android pie.
![image](https://user-images.githubusercontent.com/7713080/57703115-f5f01c00-7691-11e9-8d53-b73b20237244.png)

**Comment by adolfintel** [comment]
Ok, I'll scale down the icon a little bit

**Comment by adolfintel** [comment]
@2xlink @nichbar Can you test this APK before I release it?
[test.zip](https://github.com/adolfintel/OpenPods/files/3178628/test.zip)

**Comment by nichbar** [comment]
@adolfintel Here comes the screenshot
![image](https://user-images.githubusercontent.com/7713080/57712305-eb8a4e00-76a2-11e9-8fed-cd4e75bf7de3.png)

**Comment by adolfintel** [comment]
Looks good. I've also forced the colors in the notification to "fix" #13, waiting for feedback from that guy and then I'll push this to master

**Comment by 2xlink** [comment]
Thanks, looking good :) 

I had some thoughts about the icon, I think it looks a little bit like a musical note. What do you guys think of two airpods, like this:
![notification_icon](https://user-images.githubusercontent.com/8763936/57858254-fce17080-77f0-11e9-88d2-dddc4b7b7678.png)

**Comment by adolfintel** [comment]
Looks good, want to send a PR?
