### ISSUE TITLE
Doesn't work with the new AirPods Pro Gen. 2

### ISSUE THREAD

**Issue by NameTakenWasTaken** [adolfintel/OpenPods#150]
On a one plus 8 pro with the newest software, however I don't think it's my device. Anyone know when an update is coming?

**Comment by Electric1447** [comment]
Send BLE captures from a debug build

**Comment by NameTakenWasTaken** [comment]
Any guide on how to do this? I would love to help, but I'm afraid I don't know what you're talking about.

**Comment by Electric1447** [comment]
Enable usb debugging on your device.

Then build the app yourself and you will see debug logs from amdroid studio.

Send a few of them.

**Comment by NameTakenWasTaken** [comment]
I'm not a developer, I have no idea where to even start, I'm afraid it's gonna have to get more specific than that if I am to be of any help.

However, isn't the issue obvious? Or well, no the method of fixing, but the actual problem is just that the Gen. 2 AirPods haven't been added to the code yet or something like that. I don't know how my help would, well, help.

**Comment by Electric1447** [comment]
The airpods pro gen 2 havent been added yet.

**Comment by nixtar** [comment]
I just got a pair of pro 2's. I'll see what I can get this weekend from a debug build.
Let me know if there is anything else you would like me to run/test.

**Comment by d4rken** [comment]
We did the leg work already to add support for them to CAPod (d4rken-org/capod#31). 

I'm happy to share.

The AirPods Pro 2 identifier is `0x1420` and so far they decode the same as AirPods Pro Gen 1.

Here is example data and two test-cases:

https://github.com/d4rken-org/capod/blob/c3d4500e3a759e0679cfd788191b314286516688/app-common/src/test/java/eu/darken/capod/pods/core/apple/airpods/AirPodsPro2Test.kt#L9-L79

**Comment by Electric1447** [comment]
Fixed in 1.9
