### ISSUE TITLE
Airpods 2nd gen don't work

### ISSUE THREAD

**Issue by kolaente** [adolfintel/OpenPods#17]
I'm not sure if this is maybe out of scope for this project. However, Airpods from the 2nd gen don't work, mostly the battery status is not displayed.

**Comment by adolfintel** [comment]
Yes, I am aware of this. 2nd gen airpods use a different protocol and I don't think anyone has reverse engineered it yet. I don't have them so I can't try

**Comment by kolaente** [comment]
> I don't think anyone has reverse engineered it yet

ouh, bummer. Anything how we could help you with that?

**Comment by adolfintel** [comment]
If you have some reverse engineering experience you can try to figure it out. We need to know something about the protocol, and how to make android detect this data since it's not sent over the standard bluetooth connection or BLE

**Comment by maxtauro** [comment]
https://github.com/adolfintel/OpenPods/pull/18

**Comment by jffernandez** [comment]
@adolfintel @maxtauro Nice work! Waiting for a release with 2nd gen support!

**Comment by adolfintel** [comment]
If anyone wants to try it, this is a test build with 2nd gen support: 
[app-release.zip](https://github.com/adolfintel/OpenPods/files/3418834/app-release.zip)

Let me know if it works

**Comment by sbh96** [comment]
> If anyone wants to try it, this is a test build with 2nd gen support:
> [app-release.zip](https://github.com/adolfintel/OpenPods/files/3418834/app-release.zip)
> 
> Let me know if it works

thanks, that's work! 
can u send android code or update OpenPods project to support this  2nd gen

**Comment by adolfintel** [comment]
Awesome. The new code is in the gen2test branch at the moment. I'll give you a few more hours to test it, then I'll merge it with master and push it to F-Droid.

**Comment by sbh96** [comment]
> Awesome. The new code is in the gen2test branch at the moment. I'll give you a few more hours to test it, then I'll merge it with master and push it to F-Droid.

thanks for response fast .i hope to see your commit very soon.

**Comment by sbh96** [comment]
> Awesome. The new code is in the gen2test branch at the moment. I'll give you a few more hours to test it, then I'll merge it with master and push it to F-Droid.

can you explain how I can do reverse engineering and sniff Bluetooth to add gestures detection in the project?

**Comment by adolfintel** [comment]
Sniffing BLE is easy, you just listen for beacons. Sniffing a bluetooth connection is a bit more complicated, you need a bluetooth adapter that supports it and something like wireshark to capture the data, then do the reverse engineering.
It's complicated, and I suck at reverse engineering so it's a miracle I got this far to be honest.

**Comment by adolfintel** [comment]
Version Alpha 8 released, it might take a few days before it's available on F-Droid.
