### ISSUE TITLE
Background Notification uses wrong icon

### ISSUE THREAD

**Issue by ProtoFreeze** [adolfintel/OpenPods#173]
Not a huge issue, correct info is being shown, but the icons are wrong on the notification. I'm using the latest gen airpod pro 2's, and the notification uses the image for the airpod gen 1.
![Screenshot_20231201-165545_Chrome](https://github.com/adolfintel/OpenPods/assets/76757381/db054d39-59eb-413b-9643-b64f926d602b)

**Comment by ProtoFreeze** [comment]
I've noticed lately that the app also shows an icon for beats or nothing at all for seemingly no reason at different times

**Comment by willyum86** [comment]
I just downloaded the app it's great but I also have this problem. 
![Screenshot_20231220-173143](https://github.com/adolfintel/OpenPods/assets/154407231/98573213-df4e-4f82-abf1-3d50e5a43c4d)

**Comment by Electric1447** [comment]
Fixed in version 1.10
