### ISSUE TITLE
Add gestures?

### ISSUE THREAD

**Issue by uNbAs** [adolfintel/OpenPods#19]
Sorry, this not is a issue, but is a one feature request, ist possible add typicaly gestures? for for tap

thanks!

**Comment by adolfintel** [comment]
It would be nice but I don't know how to do it at the moment, it probably requires more reverse engineering.

**Comment by uNbAs** [comment]
Thanks for your reply

**Comment by adolfintel** [comment]
Let's leave the issue open in case someone wants to try to implement it

**Comment by tacticalDevC** [comment]
Theoretically it seems to be totally possible. Today I saw an app on Play Store which claims that it can do it. Feedback doesn't seem bad at all. Maybe it is already possible?

**Comment by ilyesAj** [comment]
trigger assistant app can do it but its a paid feature

**Comment by jokerknight** [comment]
it's a way to ”pause/play“ media when i insert to my ear or leave from my ear ？

**Comment by adolfintel** [comment]
Superseded by #58
