### ISSUE TITLE
Battery status keep loading or display wrong number -- gen2

### ISSUE THREAD

**Issue by stormrise** [adolfintel/OpenPods#21]
In MIUI Global, the battery either always shows 100%  both, or keep loading, have no response, I have already set no restriction for this app,

**Comment by stormrise** [comment]
update: I notice its decrease by 10%, now 90%

**Comment by adolfintel** [comment]
Airpods actually use only 1 digit for the battery percentage, the second one is completely faked by other apps, including iOS.

Not sure about the loading part, I thought it was fixed months ago, is it still doing it?

**Comment by stormrise** [comment]
> Airpods actually use only 1 digit for the battery percentage, the second one is completely faked by other apps, including iOS.
> 
> Not sure about the loading part, I thought it was fixed months ago, is it still doing it?

understand, thanks for you information 
the loading seems ok, it finally come out after dozens seconds
I will have more test

**Comment by adolfintel** [comment]
Ok, I'll close the issue for now but let me know if you're still having trouble
