### ISSUE TITLE
Issues after restart 

### ISSUE THREAD

**Issue by Nicktheslick69** [adolfintel/OpenPods#23]
I am having problems with OpenPods sending notifications after a restart. I am on a Oneplus 7 pro and I have to reinstall the OpenPods app to get it working again.

**Comment by adolfintel** [comment]
I cannot reproduce the problem, is there anything specific to your ROM or unusual installed apps that could cause this? (power saving, permission managers, ...)

**Comment by Nicktheslick69** [comment]
I have not changed the factory ROM build, it should be Oxygen OS 9.5.9.GM31CB . I have some other apps from f-droid: Blokada VPN(Isn't on all the time), Clover, Download Navi, Etar, OSMAnd+, Moonlight, NewPipe, Orbot, Slide, and Tachiyomi. Mind you the first thing I looked for when swapping from Iphone was an airpods notification app, I downloaded your app a while back before I had most of these other apps installed and it still did not work then. I just reinstalled it recently to see if you had fixed it but it seems like its my problem not the app's.

**Comment by adolfintel** [comment]
I don't know, it's the first time I hear about this problem.

The app is registered to start on boot, if for some reason it doesn't receive it, there's little I can do about this. The only alternative I can suggest is to not hide the app icon and run OpenPods manually after booting the phone, this should be enough to start the service.

**Comment by Nicktheslick69** [comment]
Thank you for the quick replies. I had thought of doing it manually but to me it's kind of counter-intuitive. I just wanted to be able to startup my phone and have it launch as described. Thank you for helping.

**Comment by adolfintel** [comment]
Well the app is [supposed to start on boot](https://github.com/adolfintel/OpenPods/blob/35a9d96398e8a9bd597c146e5462c44df678b615/OpenPods/app/src/main/AndroidManifest.xml#L34), and it does on every device that I tested it on.

Unless you explicitly denied the permission to start on boot in the settings, the bug is probably caused by OxygenOS and you should report it on their forum, and maybe find some other more popular app that does not properly start on boot.

**Comment by adolfintel** [comment]
Also, if you know how to use logcat, I can send you a debug build of the app and we can see if anything interesting happens on boot.

**Comment by Nicktheslick69** [comment]
As I said I have just swapped from iphone so I am not too familiar with the ins and outs of android, I may still be able to follow instructions with the debug build installed but I'd have to do it when I come home today. Thanks again I will be messaging you alter today.

**Comment by adolfintel** [comment]
Logcat is a development tool so it's part of android studio so it's not the easiest thing to do. If you don't want to do this, it's fine, but here's the instructions if you want to try:
* [Download and install android studio ](https://developer.android.com/studio)
* On your phone, go to Settings > About phone and tap Build number repeatedly until it says you're a developer
* Go back and go to System > Advanced > Developer options and turn on Android debugging (adb)
* Connect the phone to your PC
* Download the OpenPods source code and load it in android studio (will take some time)
* Uninstall OpenPods from F-Droid
* Click on the "play button" at the top
* At the bottom, click logcat
* After the app is configured and running on your phone, reboot it, then copy all the output from the logcat window.

Here's a screenshot of what it should look like (it will be very long):
![image](https://user-images.githubusercontent.com/16307689/63094296-39e00f00-bf68-11e9-8531-b967b61037bb.png)

**Comment by Nicktheslick69** [comment]
![image](https://user-images.githubusercontent.com/21070431/63142007-edbbbb80-bfb5-11e9-8270-a353641b8e22.png)
![image](https://user-images.githubusercontent.com/21070431/63142037-252a6800-bfb6-11e9-8514-d3d0a5ce38c6.png)
![image](https://user-images.githubusercontent.com/21070431/63142056-3a06fb80-bfb6-11e9-9b56-978f68997061.png)
Rebooted twice and got this error both times.

**Comment by adolfintel** [comment]
Thanks for taking the time to do that, I will investigate this error ASAP.

**Comment by adolfintel** [comment]
I've implemented an alternative method to start on boot.
Here's a test APK for you: [app-debug.zip](https://github.com/adolfintel/OpenPods/files/3508317/app-debug.zip)

It's a debug build so you can use logcat on it, you just install it and connect your phone, no need to press play.

Before you report it as working, please test it for a few hours because I suspect this breaks more things than it fixes.

**Comment by adolfintel** [comment]
New test version, should be more stable: [app-debug.zip](https://github.com/adolfintel/OpenPods/files/3508973/app-debug.zip)

**Comment by Nicktheslick69** [comment]
Hell yeah no problem as long as I could help!

**Comment by Nicktheslick69** [comment]
Thank you I will try these out later, today is Friday so I am open all
weekend to fix this after I come home.

**Comment by Nicktheslick69** [comment]
I just finished a quick test before leaving and Im pretty sure whatever you did just fixed the problem, I will test it again but it works after a restart.

**Comment by adolfintel** [comment]
So far it seems to work but it stops receiving bluetooth events after a while for some dumb reason. I have to figure that out then I'll post another test version

**Comment by Nicktheslick69** [comment]
Ok, I'm running the build on my phone and will tell you what happens
throughout the day when I get back.

**Comment by adolfintel** [comment]
Last one, I promise: [app-debug.zip](https://github.com/adolfintel/OpenPods/files/3509998/app-debug.zip)

This one is based on a workaround for your problem that I found in another repo.

**Comment by Nicktheslick69** [comment]
It's seriously no problem I enjoy the troubleshooting. The old debug build
I installed this morning just stopped working like you said it would, I
will have to wait until around 4 to install the newer version when I get
home. I appreciate it.

**Comment by Nicktheslick69** [comment]
![image](https://user-images.githubusercontent.com/21070431/63204482-13a09900-c066-11e9-842a-fb069ab59ac9.png)
![image](https://user-images.githubusercontent.com/21070431/63204487-20bd8800-c066-11e9-9902-a23d0104f8fb.png)
Looks like you struck money with that last one, doesn't look like this debug build is causing any errors but I will let the android dev be the judge.

**Comment by adolfintel** [comment]
So this new version works properly on your phone?

Also what is up with that error about not having ACCESS_COARSE_LOCATION? Did you deny the permission?

**Comment by Nicktheslick69** [comment]
This new version works just fine on my phone, I have not denied the app any permissions so I have no clue as to why it's giving me that error.

**Comment by adolfintel** [comment]
Well, what matters is that it works. Do some more testing in the next 1-2 days if you can, then I'll release it officially with some other minor improvements.

**Comment by adolfintel** [comment]
Thanks for helping me sort this out.

**Comment by Nicktheslick69** [comment]
Sounds good!

**Comment by Nicktheslick69** [comment]
Should I have the blank openpods notification in the notification center without the airpods connected and Bluetooth off? Photo attached is what I'm talking about.

**Comment by adolfintel** [comment]
No, that's definitely not supposed to be there. Does it go away if you connect your airpods or turn bluetooth on/off?

**Comment by adolfintel** [comment]
Here's another test version: [app-debug.zip](https://github.com/adolfintel/OpenPods/files/3511680/app-debug.zip)

If this doesn't work, I'm completely out of ideas and you'll have to report this issue to oneplus

**Comment by adolfintel** [comment]
I just had another idea. This version is the same as the one on F-Droid, except it tells the system that it's from the Android 6.0 era, before that error message was introduced. See if it works:[app-debug.zip](https://github.com/adolfintel/OpenPods/files/3511702/app-debug.zip)

**Comment by Nicktheslick69** [comment]
> I just had another idea. This version is the same as the one on F-Droid, except it tells the system that it's from the Android 6.0 era, before that error message was introduced. See if it works:[app-debug.zip](https://github.com/adolfintel/OpenPods/files/3511702/app-debug.zip)

This build has been working flawlessly but I will let you know what happens (if anything) by tomorrow.

**Comment by adolfintel** [comment]
Awesome. This build has the added advantage of not being allowed on Google Play so assholes can't sell it (it happened)

**Comment by Nicktheslick69** [comment]
That is really gross, did you just see your app for money one day on the store? [Here is a pastebin of the app running ](https://pastebin.com/tRkxfqdw)

**Comment by adolfintel** [comment]
More than once, I had to send at least 5 or 6 DMCA takedowns in the last 5 months

**Comment by Nicktheslick69** [comment]
Thank you for all of the wonderful help, I enjoyed learning how to debug software on android. If the problem occurs again I will reopen the thread but I am pretty sure you just fixed it for good. I wish you the best of luck in taking down all the copycats stealing the source code and re-uploading it, Thanks again for walking me through it and taking the time to fix a bug that could go easily ignored, I appreciate it.

**Comment by adolfintel** [comment]
No problem, thanks for helping me debug this issue

**Comment by adolfintel** [comment]
I was looking at the source code for GadgetBridge, an app to connect smartwatches and stuff like that, and I noticed that it uses a very similar mechanism to start on boot as OpenPods.

Can you try installing it from f-droid to see if it has the same problem when you reboot the phone? If it has the same bug, you'll know because you won't see a toast message saying "Bluetooth is disabled" after booting.

**Comment by Nicktheslick69** [comment]
I just installed GadgetBridge and after a reboot I got no toast notification saying bluetooth was disabled.

**Comment by adolfintel** [comment]
@Nicktheslick69 So it is a bug in OxygenOS. You should report it on their forum, tell them that GadgetBridge and OpenPods fail to start on boot with a permission error.

**Comment by Nicktheslick69** [comment]
Unfortunately I have to wait 15 days until I can post on the oneplus forum app since I have just registered.

**Comment by adolfintel** [comment]
Wow that sucks

On August 18, 2019 5:09:50 PM GMT+02:00, Nicktheslick69 <notifications@github.com> wrote:
>Unfortunately I have to wait 15 days until I can post on the oneplus
>forum app since I have just registered.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/OpenPods/issues/23#issuecomment-522329912

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
