### ISSUE TITLE
Make it hard or impossible to upload to Google Play

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/OpenPods#24]
I don't want this app to be distributed through Google Play so I'm looking for ideas on how to make it hard or impossible to do it. This is because I noticed that some assholes redistributed this as a paid app or with ads, without even crediting the original app, and I had to send several DMCA requests.

So far, here's what I came up with:
* The app already intentionally violates Google Play policies on disabling battery optimization but they don't seem to actually check this
* Setting the app's target SDK to less than 26 (minimum for Google Play) and make sure the background service breaks if SDK 26 or newer is used

Ideas?

**Comment by Poussinou** [comment]
Hi, @adolfintel , as you can see on my profile, I sometime spend some time to track fake developers that are stealing open source apps like yours. I would like to get the links to the apps and to the fake developers. You can put them here or contact me on [Reddit](https://www.reddit.com/u/Poussino)      I saw your article [here](https://www.reddit.com/r/fdroid/comments/crxby0/prevent_people_from_reuploading_my_app_to_google)

**Comment by ceifa** [comment]
I don't understand, why you guys don't want it on Google play? Isn't it just a matter of fixing this battery optimization issue?

**Comment by adolfintel** [comment]
The battery optimization problem would get the app constantly banned/unbanned, but the most important reason is that I just don't want people uploading this to google play claiming that they made it, so the app can detect if it was downloaded from google play and break itself after a while.

**Comment by jasondyoungberg** [comment]
Note that it's completely legal to reupload this to Google Play as a paid app. The only requirements are basically just that they must provide attribution and the modified source code.
