### ISSUE TITLE
A question about battery values

### ISSUE THREAD

**Issue by sergeyfitis** [adolfintel/OpenPods#25]
Hi. Thanks for your contribution to the opensource android community.
I have a question regarding how battery values are encoded inside the payload.
You said they are storing in range 0-10(0-100%, step 10). But how the iPhone shows battery charge with step by 1%?

Maybe you could recommend some resources about the reverse engineering of AirPods signal?

Best regards,
Serhii.

**Comment by adolfintel** [comment]
Hi,
I did the reverse engineering myself so all I know is in the comments in PodsService.java

According to my reverse engineering, the second digit is a completely faked and the airpods only use 1 digit to represent the battery level. I might be wrong though, I'm not really an expert at reverse engineering; maybe someone can find this mysterious second digit.

**Comment by sergeyfitis** [comment]
Thanks for your reply. I will try to debug the headphones too when my AirPods arrive.
If you do not mind, I will play around with the source code of your application. Maybe I'll find out something else.

**Comment by adolfintel** [comment]
Sure, it's open source for a reason. Let me know if you find something

**Comment by sergeyfitis** [comment]
Sure. I will let you know if any.

**Comment by huseyint** [comment]
has anyone figured out how iOS widget shows a finer detail value, and not the increments of 10?

**Comment by adolfintel** [comment]
@huseyint No, It's either completely fake or it is not sent via BLE. I suspect the first because it behaves kinda erratically with older airpods with worn out batteries.
