### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by jockebq** [adolfintel/OpenPods#33]
First off, I am so happy I found this app, tried every app in the Play Store, and everything is trash. Great work with this one! Just what's needed and no bloatware.

Using this on my Note 10 with Dark mode enabled, but the notification is white. Would it be possible to have a Dark mode for the notification?

Here's an example of a Play Store app doing dark notifications: https://lh3.googleusercontent.com/qx861-4RgJ_KpAV8LUC9z6yncolCLaVg0y_3YKDy3r_rrWTbCPYJr4dQzKCEYy3kCIo=w1920-h978

Thank you!

**Comment by adolfintel** [comment]
Yes, I can add this in one of the next updates.

**Comment by AykutCevik** [comment]
I can confirm that the notification is dark as well while on Android 10 and enabled dark mode from system.

**Comment by Domi04151309** [comment]
With the current app version Android 10 uses a fallback for apps that don't fully support dark mode, which invertes the colors of the notification, @AykutCevik.

**Comment by adolfintel** [comment]
Implemented in #65
