### ISSUE TITLE
AirPods 2 are not detected.

### ISSUE THREAD

**Issue by f0s3** [adolfintel/OpenPods#35]
Hi. I've downloaded your app using the direct link provided in the readme, and opened my Airpods 2 case when they are connected to the bluetooth and gps is turned on(just in case it is needed), allowed all the app wanted me to, yet there is no notification while I have your app opened on my Xiaomi Redmi 6. I am a developer myself, so if any additional info needed (data from android studio or anything else that might show why the app doesn't seem to detect the pods even though the music is playing through them), please let me know. IPhone 8 shows the firmware version as 2A364, were 1A661 before iphone has auto updated them.

**Comment by adolfintel** [comment]
Were they detected before the firmware update?

**Comment by f0s3** [comment]
I'm not sure about this one, but I tried different apps from play market and none seemed to display battery status neither before firmware update nor after it.

**Comment by f0s3** [comment]
Note that I have connected my phone to my laptop (ThinkPad x220 if it matters), and can now debug your application. I will leave the logs from the application below:

**Comment by f0s3** [comment]
After a bit of debugging I've found out that this if has both `maybeConnected` and `!(leftStatus==15&&rightStatus==15&&caseStatus==15)` in it, thus the notification is not shown. Here is the file:line I am talking about. https://github.com/adolfintel/OpenPods/blob/ffd9bdcf89af5bed8de50a19aaadf0468438ff4e/OpenPods/app/src/main/java/com/dosse/airpods/PodsService.java#L257

**Comment by adolfintel** [comment]
That is very strange, keep me posted on this ;)

**Comment by f0s3** [comment]
Maybe we can meet in skype and reverse-engineer together? It's difficult to read PodsService because it's way to much code in one file, so I'll refactor it once I get this working. I also think that it might be nice to lint the project according to the Java codestyle, and maybe some unit tests (if you want it to happen, of course). Though its a topic for another issue. Anyways, my skype is dima_kovpak.

**Comment by adolfintel** [comment]
Sure, if you have some time to spare and want to improve the codebase, feel free to do it and send a PR.
I should point out that you're the only person to have reported this issue with airpods 2, in fact a guy reported the app to be working with the new airpods pro.

**Comment by f0s3** [comment]
Could we meet in skype?

**Comment by f0s3** [comment]
I will try to get my friends' airpods 2 today to make sure it is my android and not my pods. I also have two more phones except my main one, maybe it is worth testing on them.

**Comment by adolfintel** [comment]
I normally don't use skype, but I can use it as a last resort. If you need to contact me directly, I prefer to use telegram, [dosse91](https://t.me/dosse91)

**Comment by f0s3** [comment]
Ok, let it be telegram. I don't use it either as it's a microsoft product and I also use it as a last resort. I just wanted to share my screen with you so we can debug that together. What I have found out that when connecting my pods to Xiaomi Redmi Note 5, AirBattery from play market, it detects my pods and shows percentages of case and each of the pods right away. I will try to use Redmi Note 5 with OpenPods and debug the correct behaviour to know what to expect from my phone (what should happen on my Redmi 6). Also note that I tried my friends' airpods 2 and they seem to have same problem on my phone (Redmi 6).

**Comment by f0s3** [comment]
I will write about the progress of this issue briefly to keep the log of the work been made and the results. I have tried flashing Lineage OS 16.0 on my Redmi 6 and it bootlooped two times I tried, that's why I rolled back to the stock MIUI. There is no official support for my phone from any ROMs,  except for the stock one, of course. It seems to be a ROM issue as it starts and then stops listening the data immediately after the start. I might wanna try to flash a miui with android 8.1 (one MIUI version before my current (10.4.4) - it's 10.3.6), as I have some other problems after updating, so it would fix them as well as (supposedly) bluetooth issues. I'm not sure if I will flash the 10.3.6 though, but I might give it a try one day I think. And of course, @adolfintel, I'm extremely grateful f or your help and guidance on flashing the ROMs. You've taught me very valuable things. I will reopen this if it ever gets solved by flashing the MIUI 10.3.6 or any other way. Closing this issue for now.

**Comment by f0s3** [comment]
@adolfintel I have flashed the 10.3.6, and even though airbattery started working on my phone and shows battery status of my pods but not the case, openpods doesn't show any notification. I recon it's because there is an if clause which looks on the case as well as both pods, and as airbattery doesn't show my case battery status, that's why the notification doesn't show up. I will debug why can't I get the case status but maybe we should add a fallback variant to show at least what we can and not when all of the battery levels are known. I will debug it later as I'm at work now.

**Comment by f0s3** [comment]
```D/AirPods: BT ON
    START SCANNER
D/BluetoothAdapter: isLeEnabled(): ON
D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=5 mScannerId=0
D/BluetoothHeadset: Proxy object connected
D/AirPods: BT PROXY SERVICE CONNECTED
D/AirPods: ACL CONNECTED```

Here is what I have now. Still no notification as all statuses are at 15.

**Comment by adolfintel** [comment]
Didn't we already determine that it was a ROM bug?

**Comment by f0s3** [comment]
Yes, but I flashed the MIUI 10.3.6 (Previous version, on which sometimes it works somehow), and now the logs are different.

**Comment by f0s3** [comment]
I flashed the lineageos 16.0 (android 9), and it doesn't work. seems to be an issue with android 9 on my device(redmi 6). I will flash the lineageos 15.0 based on android 8.1 and it should work. Posting here just for future reference.
