### ISSUE TITLE
Update readme with what languages are supported?

### ISSUE THREAD

**Issue by f0s3** [adolfintel/OpenPods#36]
I speak Russian, Ukrainian, English and some Swedish (not fluent though) and may help translating your app. I suggest that we keep track of the languages supported in the README.md.

**Comment by adolfintel** [comment]
That would be great. Do you know how to translate an android app or do you need help with it?

**Comment by f0s3** [comment]
I think I know, I will let you know if I need any help.

**Comment by f0s3** [comment]
I think I know, I will let you know if I need any help.

**Comment by f0s3** [comment]
We also need to add the section about what languages are already supported.

**Comment by adolfintel** [comment]
Thanks for the 2 translations you sent in. If you want you can send a PR with an updated readme, should take just a few seconds.
