### ISSUE TITLE
Fake AirPods

### ISSUE THREAD

**Issue by MaximilianGaedig** [adolfintel/OpenPods#39]
Will you try to implement fake AirPods?
Or can you give a hint how you discovered how to get the percentage on the real ones?

**Comment by adolfintel** [comment]
I assume they send their status via BLE, like the real ones.
You have to make a simple BLE scanner app and look at what data is being sent from the fake pods over time and figure out which bytes are the percentages.
It takes some time.

**Comment by MaximilianGaedig** [comment]
Where would the percentage be reported? Here is the hex i got from debug: 071901022055AA563100006FE4DF10AF106081033B76D9C7112288
