### ISSUE TITLE
Check on case charging status 

### ISSUE THREAD

**Issue by AeliusSaionji** [adolfintel/OpenPods#4]
The airpods are always broadcasting battery status while the case is plugged in. Would be nice to be able to check on the % charge the case is at without having to connect.

**Comment by adolfintel** [comment]
The case doesn't send the status unless there's at least 1 airpod in it, it just says not connected

**Comment by AeliusSaionji** [comment]
Yes, but while the airpods are in the case and the case is charging, it _will_ be transmitting said data.

**Comment by adolfintel** [comment]
From my testing, the case sends the status if it's open and there's at least one airpod in it, whether it's charging or not. As soon as you close it or take out the airpod, you don't get the status anymore.
You could store it and display it while it's not broadcasting it, but it would be inaccurate. Is that what you meant?

**Comment by AeliusSaionji** [comment]
![](https://i.imgur.com/cjxPku8.jpg)
![](https://i.imgur.com/dOMByIc.png)

**Comment by AeliusSaionji** [comment]
The data updates. It just jumped from 65% to 75% without my touching the case. It might be on a 30s-60s interval, but it is transmitting the data. This app can read it.

**Comment by adolfintel** [comment]
Why the fuck don't mine do that? I'm charging the case right now but I don't see anything on an iPhone

**Comment by adolfintel** [comment]
What app is that?

**Comment by AeliusSaionji** [comment]
[AirBattery](https://play.google.com/store/apps/details?id=friedrich.georg.airbattery).

It initially says the airpods are not connected, but if I leave it open for 30s or so, it will get an update on the charge status.

**Comment by adolfintel** [comment]
I'm taking a look at that application, there are some similarities with mine but it's also a lot more sophisticated (also I hope you're not allowing it to go online because it's full of trackers). I'm trying to figure out what we're doing different in the decoding of the status right now.

**Comment by adolfintel** [comment]
Man I'm just too dumb for reverse engineering 😂
Do you want to take a look and see if you can find where that magic case status is?

**Comment by AeliusSaionji** [comment]
Not my area of expertise, but an iPhone user told me you can see this on iPhone via the battery widget.

**Comment by AeliusSaionji** [comment]
![](https://i.imgur.com/EZvZpKh.jpg)

**Comment by adolfintel** [comment]
Yea, it doesn't show on mine, I can only see the airpods, and the case when there's one in it, so I don't know where that variable is stored. I will try to do some more reverse engineering but I really suck at it, no guarantees.
