### ISSUE TITLE
Occasional Blank notification popup with airpods pro

### ISSUE THREAD

**Issue by prg318** [adolfintel/OpenPods#40]
Hello,

First of all, thank you for your work on this project.

Today, with my airpods pro, I am receiving a completely blank OpenPods notification (there are two notifications here - one for openpods, and a second one for kdeconnect):

- https://xannode.com/openpods-screenshot.png

I'm using LineageOS 9 on a Pixel XL 128GB.

I tried clearing the storage for openpods, but the issue remained.

I just got my Pro Airpods yesterday and didn't have the issue until today - not sure what has changed.

Please let me know if there is any additional information I can provide to assist in resolving this issue.

Cheers!

**Comment by prg318** [comment]
Just noticed something on my lock screen:  there is white on white text that reads "You need to turn on Location to allow OpenPods to read the status"

The white text on white bubble is barely visible on the lockscreen, but completely invisible when unlocked (as shown in the previous screenshot)

After turning on location, I see the battery status of my airpods

Just out of curiosity - why is location required for this?

**Comment by adolfintel** [comment]
Hi,

Not sure why the text is white on white, but I'll check the layout for that notification.

Location is required because some genius at google thought it was a good idea to put BLE under location, so even if bluetooth is enabled, you can't access BLE without turning on location. It will work regardless of the level of precision that you select.

**Comment by adolfintel** [comment]
Try the new version here: https://github.com/adolfintel/OpenPods/releases/tag/1.1

**Comment by prg318** [comment]
Just tested new version - works great.  I can read the text on both the unlocked screen and locked screen even with the LOS Dark theme

Thanks for looking into this and thanks for the explanation!  Much appreciated

**Comment by mentalisttraceur** [comment]
Any chance of getting the 1.1 pushed to FDroid soon? I just hit this bug since I just downloaded the app for the first time.

**Comment by adolfintel** [comment]
@mentalisttraceur F-Droid always takes a while to update, but the update has already been pushed.

**Comment by mentalisttraceur** [comment]
@adolfintel Okay great, thanks for letting me know.
