### ISSUE TITLE
Unhide?

### ISSUE THREAD

**Issue by mentalisttraceur** [adolfintel/OpenPods#42]
So I accidentally did the "hide app" action in the app settings. How do I un-hide it?

Any chance you could document some pointer about how to undo the app hiding either in the app itself or at least in the README?

**Comment by mentalisttraceur** [comment]
I fixed this for myself by uninstalling and then reinstalling the app.

Not sure if that's the official/proper solution, but whatever that solution is, it would have been helpful to see it somewhere along the path between hitting the "hide app" button and the app actually hiding.

**Comment by adolfintel** [comment]
The only way to unhide it is to reinstall the app.
Even if I added an option to unhide it in the settings, you wouldn't be able to reach it because the app is hidden.

**Comment by mentalisttraceur** [comment]
So like I said:

> would have been helpful to see ["the only way to unhide is to reinstall"] somewhere along the path between hitting the "hide app" button and the app actually hiding.

**Comment by adolfintel** [comment]
Will add in the next update ;)
