### ISSUE TITLE
Powerbeats Pro - Working

### ISSUE THREAD

**Issue by flawedworld** [adolfintel/OpenPods#44]
Hi, I am pleased to report that my Powerbeats Pro earbuds are fully functional with the app. No issues thus far. Minor enhancement would be purely cosmetic and thats just changing the icons from airpods to the powerbeats art. Please let me know if you would like any debug info. Thank you for your work.

**Comment by adolfintel** [comment]
That's great. Can you provide some logcat output so I can try to detect them? I can help you out if you don't know how to do it

**Comment by flawedworld** [comment]
Sure, I will see if I can grab a logcat from ADB of me pairing them. Will report back tomorrow if all goes well.

**Comment by flawedworld** [comment]
@adolfintel ADB logcat output is here  https://ghostbin.co/paste/vnepk64n , password is OTNkdThqbmRrd2FramQK , hope it helps!

**Comment by adolfintel** [comment]
You need to run the application from android studio, release builds like the one on F-Droid don't output anything to logcat

**Comment by jakuski** [comment]
Hi,

I'm posting under this thread as its very similar. My Beats Studio3 wireless also work with this app and shows its battery level next to the right airpod.

**Comment by adolfintel** [comment]
This is really good. I need some logcat captures to be able to correctly detect them and show the correct images. Do you know how to do that?

**Comment by mikziel** [comment]
I can also confirm that my BeatsX are working with this app. The percentage is valid but it is shown only next to to the right airpod just like @jakuski said. I'm open to making logcat capture in android studio but I don't know how to do it properly.

**Comment by Electric1447** [comment]
Added support for powerbeats pro
