### ISSUE TITLE
AirPods Pro pictures on notification bar

### ISSUE THREAD

**Issue by Hazuka** [adolfintel/OpenPods#49]
Hi, and amazing job for this fantastic little app. I wanted to know if there were plans to display the right types of headphones in the notification bar? It's still good More class to have the images of the Airpods pro when they are connected. Thanks again for the job contributed here!
![Screenshot_20200110-095145](https://user-images.githubusercontent.com/17553127/72139298-d3ccac00-338e-11ea-9508-9c46ab042c15.jpg)

**Comment by adolfintel** [comment]
I pushed an update with this feature about 2 weeks ago but F-Droid is taking its sweet time to update it. You can download the APK directly from here: https://downloads.fdossena.com/geth.php?r=openpods-apk

**Comment by Hazuka** [comment]
I can't open the link. once opened, a blank page opens then closes without downloading ...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Hazuka** [comment]
![Screenshot_20200110-101454](https://user-images.githubusercontent.com/17553127/72141027-4c813780-3392-11ea-9174-8e3354161d6c.jpg)

**Comment by adolfintel** [comment]
Shit, no wonder you didn't get the update from F-Droid. I pushed the commit to master but didn't make the release. Damn it. I'll send you a new link in a few minutes

**Comment by Hazuka** [comment]
Ok i wait :)

**Comment by Hazuka** [comment]
Are you compiling the program? Anyway, no worries about the delay, at least it will be good on github haha
![Screenshot_20200110-104756](https://user-images.githubusercontent.com/17553127/72143259-aedc3700-3396-11ea-94d0-3f528b98c03d.jpg)

**Comment by adolfintel** [comment]
Done. You can download the APK from the previous link or wait a few days for F-Droid to build it

**Comment by Hazuka** [comment]
> Done. You can download the APK from the previous link or wait a few days for F-Droid to build it

I love you bro!
![Screenshot_20200110-105249](https://user-images.githubusercontent.com/17553127/72143649-5ce7e100-3397-11ea-8a2f-5a7621c41e22.jpg)

**Comment by adolfintel** [comment]
Perfect ;)
