### ISSUE TITLE
Inverted colours in Pixel 3 dark theme

### ISSUE THREAD

**Issue by citifouronesix** [adolfintel/OpenPods#54]
Hi! Really love OpenPods and I've been using it since I got my phone. There's one little issue when using it with the pixels dark theme though: The whole notification is inverted, not just the background so the AirPods and Case are completely blacked out. This isn't really a huge issue but just a small cosmetic thing. Can it be fixed? Thanks! 
![Screenshot_20200125-143808](https://user-images.githubusercontent.com/49580306/73126471-ce6f8400-3f80-11ea-8a1a-77adf27111d9.png)

**Comment by adolfintel** [comment]
PR #46 should fix it. It will be merged in the next update

**Comment by citifouronesix** [comment]
Perfect, thanks!
