### ISSUE TITLE
pls help kind sir thankyou vry much

### ISSUE THREAD

**Issue by NieelsHub** [adolfintel/OpenPods#57]
It dont works on my phone  is   apple galaxy s2 phone please help thankyou

**Comment by NieelsHub** [comment]
pls      if you help i help you

 with iarpodspro issue

**Comment by adolfintel** [comment]
Your phone's rotational velocidensity is too low to run OpenPods. You can easily fix the issue by installing Gentoo GNU/Linux. For optimal results, do not install SystemD.

Regards
