### ISSUE TITLE
Show status from received beacons if location is disabled

### ISSUE THREAD

**Issue by mm3** [adolfintel/OpenPods#59]
Could you please add showing status in case then location disabled but some valid beacons received in TIMEOUT_CONNECTED time?

https://github.com/adolfintel/OpenPods/blob/9a25fae80873159f45d6afe144536e50313ac322/OpenPods/app/src/main/java/com/dosse/airpods/PodsService.java#L275

**Comment by adolfintel** [comment]
Why? It would show it for just a few seconds?
