### ISSUE TITLE
Android 10, Galaxy Note 10 - the app refuses to work if the location is turned off (while the permission is granted)

### ISSUE THREAD

**Issue by maxim-saplin** [adolfintel/OpenPods#60]
This essentially requires having the Location turned on all the time - that was the reason why I refused to use the app. AirDroid from GPLay is OK with  Location off.

P.S.: all that stuff with location permissions make a bad impression considering that app only aimed at showing battery level. I see that all GPLay Airpods apps require that permission. Though having some mode without location permission would be a killer feature to me (even if it'll require manual refreshing of the status of the app/battery).

**Comment by jffernandez** [comment]
Location is needed so the app can read BLE (Bluetooth Low Energy) packages, because that is the communication method for the device.
Is not a problem with de apps but the Android API, someone decided to put that under Location permission, even when is not really related.
You can have location off, then turn it on to see battery levels, then turn it off again.

**Comment by maxim-saplin** [comment]
Any chance to make it possible to check levels without Location OFF as with AirDroid?

**Comment by jffernandez** [comment]
To allow communication with any BLE device, like AirPods, you should grant Location permission (per Android API design), but maybe, once granted, communication is allowed with disabled location, here @adolfintel can help.

**Comment by adolfintel** [comment]
As @jffernandez said, android requires location permission to use BLE. I'm not collecting any data or anything, the app doesn't even have internet access.

I don't know how AirDroid is doing it without location permission, [according to the android documentation, you can't](https://developer.android.com/guide/topics/connectivity/bluetooth-le#permissions). Can you make sure that what you said is correct?

Anyway, when I did some investigation on similar apps on google play last year, all of them had ads and/or analytics, so I definitely wouldn't install them unless you have a firewall installed (which is what I used to do before I made this app)

**Comment by adolfintel** [comment]
I'll close the issue for now but keep me posted if you find anything

**Comment by maxim-saplin** [comment]
Please see below side by side MaterialPods OpenPods. Notice that toggling Location at the top disables OpenPods while MaterialPods keeps working. Both apps are granted location permission.

![Screenshot_20200309-174438_Nova Launcher](https://user-images.githubusercontent.com/7947027/76225864-c49a9b00-6225-11ea-883b-04b3fc8e3aff.jpg)
![Screenshot_20200309-174420_Nova Launcher](https://user-images.githubusercontent.com/7947027/76225887-c95f4f00-6225-11ea-800a-bb5e2a968911.jpg)

**Comment by adolfintel** [comment]
I removed that check, does this APK work for you? 
[app-release.zip](https://github.com/adolfintel/OpenPods/files/4307294/app-release.zip)

**Comment by maxim-saplin** [comment]
That was super fast) Yep, works like a charm!

**Comment by adolfintel** [comment]
On today's episode of google changes random shit in android...

**Comment by maxim-saplin** [comment]
Lol:) Thanks a lot!
