### ISSUE TITLE
License break on Play Store

### ISSUE THREAD

**Issue by Electric1447** [adolfintel/OpenPods#66]
https://play.google.com/store/apps/details?id=com.androidpods.airpods

This app literally uses screenshots from OpenPods

**Comment by Domi04151309** [comment]
That's some next level low effort.

**Comment by adolfintel** [comment]
Thanks for reporting it, I'll send yet another DMCA, although as you can see from the reviews, the sabotage is working as intended.

**Comment by mirh** [comment]
I understand being angry at scummy freebooters (with a non-trivial chance of being spyware or whatnot too).
But I'm having a bit of a hard time parsing how you can complain about GPL violations, aside of the sense of just them not releasing the sources.
