### ISSUE TITLE
Notification layout issues in #65

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/OpenPods#68]
@Electric1447 I merged your PR since it works well, however I noticed two issues with the new notification layout:
* When the device is set to dark mode, the background is still white, making the text unreadable (you probably forgot to remove my hacky workaround to force the colors in before dark mode was supported)
* The size of the charging icon is not consistent

Screenshots: 
![Screenshot_20200524-073834_Lawnchair](https://user-images.githubusercontent.com/16307689/82746667-aa874800-9d92-11ea-9b57-3f73000fac97.png)
![Screenshot_20200524-073921_LineageOS_Settings](https://user-images.githubusercontent.com/16307689/82746670-b2df8300-9d92-11ea-82d0-e82cc0591411.png)

I'm sure I can fix those issues myself but since it's your PR, it's probably best if you could do this to avoid introducing other glitches.

**Comment by Electric1447** [comment]
I'll work on it

**Comment by Electric1447** [comment]
For the life of my me I can't recreate this bug.

![Screenshot_20200524-092832](https://user-images.githubusercontent.com/36371414/82747401-107acc00-9da1-11ea-8bee-9ebb0365e3ce.jpg)

![Screenshot_20200524-092810](https://user-images.githubusercontent.com/36371414/82747404-12dd2600-9da1-11ea-8d98-a634cb854f27.jpg)

Maybe try to reinstall the app and test further.
(Btw which Android version are you on?)

**Comment by Electric1447** [comment]
This might be an issue for Android 9 and lower

**Comment by adolfintel** [comment]
Hmm, yes, it could be only on older versions of Android, I'm still using Android 9.
If you can find some workaround for the background color, do it, otherwise just force the notification to be white if the SDK is <29 I guess.

The charge icon problem I think is caused by the space below the pod image being too narrow when it says 100%

**Comment by Electric1447** [comment]
I created a possible fix, However I don't have an older Android phone charged up rn (and the default avd is crap) so please test it yourself.

**Comment by Electric1447** [comment]
It is not a major change the only thing changed is to force the notification background to update with the notification text.
(Google/Android should really have a more developer friendly dark theme before hyping their broken dark mode)

**Comment by adolfintel** [comment]
It works :)

**Comment by adolfintel** [comment]
I merged #69 since it works. Can you fix the charge icon as well?

**Comment by Electric1447** [comment]
First I'll need to charge my Airpods ;)

**Comment by Electric1447** [comment]
I fixed the charge icon in #70

**Comment by adolfintel** [comment]
All issues seem to have been resolved. I'll test the app for a few days to make sure that I don't run into problems (most importantly, I want to make sure that the service sticks), then 1.4 is ready for release.
