### ISSUE TITLE
Notification gets stuck under unknown circumstances

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/OpenPods#7]
For reasons that are currently unknown, occasionally, the notification will get stuck in an indeterminate state. It seems to happen randomly after the screen has been turned off for some time with the AirPods connected.
When this glitch occurs, the application becomes unresponsive to bluetooth events (switching on/off, connecting/disconnecting AirPods) and needs to be terminated and restarted.

If you're experiencing this issue, just know that I'm aware of it and the application won't reach 1.0 with this garbage bug.

**Comment by jplitza** [comment]
This happens almost always for me. I built and installed master to see if your workaround works, will report back.

**Comment by adolfintel** [comment]
Thanks. I've been testing the workaround for over a week now and I haven't had this issue yet.

**Comment by adolfintel** [comment]
It looks like the workaround works.

**Comment by jplitza** [comment]
Well, I still have that problem. I mostly use the headphones with the screen turned off, and often the notification gets stuck with the spinners showing everywhere. Only forcing the app to close and then opening it again from the app drawer can unstick it.

**Comment by adolfintel** [comment]
It's normal to see the spinners for a few seconds after the screen has been off for a while, but it shouldn't get stuck like that. How long have you waited?
Also, what rom are you using?

**Comment by jplitza** [comment]
Well, right now my Airpods haven't been connected for 10 hours, and the screen was on for several minutes. I'm using LineageOS 14.1

**Comment by adolfintel** [comment]
I'll see if I can find an old build of lineage 14.1 on my device and try to reproduce the problem
