### ISSUE TITLE
Dark Mode Issues

### ISSUE THREAD

**Issue by Domi04151309** [adolfintel/OpenPods#76]
The dark notification doesn't blend in nicely because different OEMs use different default background colors. Also, the text color isn't 100% white or black because of Material Design standards.

<img src="https://user-images.githubusercontent.com/36272047/83884738-a15c8a80-a745-11ea-9034-738e70e647b5.jpg" width="200" />

**Comment by adolfintel** [comment]
Yeah, I'm aware of this issue, the colors are forced to white or black according to the theme selected when the service is started. It's a workaround for Android <=9
I'm sure there's a better way to do it.
