### ISSUE TITLE
Remove permission requests for API ≥ 29

### ISSUE THREAD

**Issue by Electric1447** [adolfintel/OpenPods#78]
We should remove the location permission request for API ≥ 29 as it is not needed.

I'll open a PR later today if I have time.

**Comment by Electric1447** [comment]
Btw can I add labels to issues or only you can do that?

**Comment by adolfintel** [comment]
I'll add you as a developer to the project :)

**Comment by Electric1447** [comment]
After further testing, the app cannot function without location permission on all android versions.
