### ISSUE TITLE
AirPods doesn't go

### ISSUE THREAD

**Issue by dpatrongomez** [adolfintel/OpenPods#8]
Hello, I have tried to install the application and when connecting the AirPods the application does not detect them.

**Comment by adolfintel** [comment]
Are you sure they're 1st gen airpods?

**Comment by dpatrongomez** [comment]
How Can I find that?

**Comment by adolfintel** [comment]
When did you buy them?

**Comment by dpatrongomez** [comment]
2018

**Comment by adolfintel** [comment]
Ok, definitely 1st gen then. What phone is it?

**Comment by dpatrongomez** [comment]
I have a Xiaomi Mi6 (sagit), Android 9.0 AOSP

**Comment by dpatrongomez** [comment]
If you have Telegram, lets talk there https://t.me/dpatrongomez

**Comment by adolfintel** [comment]
Ok, I'll write you on telegram
