### ISSUE TITLE
ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS not working on first launch

### ISSUE THREAD

**Issue by Electric1447** [adolfintel/OpenPods#80]
If the app is closed in the first time it will kill the service.

**Comment by adolfintel** [comment]
Are you sure about this? Unless this problem was introduced recently, I remember doing tests like this last year.

**Comment by Electric1447** [comment]
Only happens in latest commit, does not happen in release 1.4

**Comment by Electric1447** [comment]
Okay I think I found the cause, it only happens on debug versions

**Comment by adolfintel** [comment]
If you close android studio it terminates the service, that might be the problem you're running into.

**Comment by Electric1447** [comment]
Compiled release version of latest version and this does not happens.

**Comment by Electric1447** [comment]
> If you close android studio it terminates the service, that might be the problem you're running into.

Maybe android studio 4.0 introduced a new bug with services?

**Comment by Electric1447** [comment]
Anyway I am closing this issue as it does not affect users

**Comment by Electric1447** [comment]
Found the issue: Google introduced a new "feature" in which if you run a app from the Run 'app' button in android studio and exit it, it will terminate the service.

**Comment by adolfintel** [comment]
Nice "feature"

**Comment by Domi04151309** [comment]
Everybody loves "features"
