### ISSUE TITLE
Serious Play Store violations

### ISSUE THREAD

**Issue by Electric1447** [adolfintel/OpenPods#81]
Found this by accidentally clicking the play store button in nova launcher
![Screenshot_20200608-191122](https://user-images.githubusercontent.com/36371414/84054501-28b33380-a9bc-11ea-86fb-5372d9a1f427.jpg)
This app uses the same package name as OpenPods this is a new level of GPL violation

**Comment by adolfintel** [comment]
Fuck, another one?
Well at least the sabotage is working as intended, look at those reviews :laughing:

**Comment by Domi04151309** [comment]
It even uses the same screenshots. Do people even try? xD

**Comment by adolfintel** [comment]
DMCA sent

**Comment by Electric1447** [comment]
This app is still on the Play Store (WITH OPENPODS PACKAGE NAME).

Maybe we should just upload an App that links to F-Droid with OpenPods package name so no one else could use that package name?

**Comment by Domi04151309** [comment]
That would violate play store policies

**Comment by adolfintel** [comment]
Hmm, it was taken down in june, they must have reuploaded it.
Either way, the app doesn't work, as expected

**Comment by Domi04151309** [comment]
You could also [check if the app was installed by the play store](https://stackoverflow.com/questions/37539949/detect-if-an-app-is-installed-from-play-store) and display a message accordingly

**Comment by adolfintel** [comment]
The app already checks it, but instead of displaying a message that could be easily found and removed, it behaves incorrectly after a few seconds.
