### ISSUE TITLE
[Bug Report] Battery drain notification

### ISSUE THREAD

**Issue by Domi04151309** [adolfintel/OpenPods#88]
After some time the system shows a "OpenPods is draining your battery" notification and the device gets a little hot. Doesn't seem intentional.

**Comment by adolfintel** [comment]
Definitely not supposed to happen. Does it happen with version 1.3 as well?

**Comment by Domi04151309** [comment]
I'll test it.

**Comment by Domi04151309** [comment]
On version 1.3 the app crashes because of the TransactionTooLargeException but does not display the battery drain notification.

**Comment by adolfintel** [comment]
Would you be able to identify the cause of the power drain? With the profiler in android studio maybe. I imagine the notification thread will be running furiously.

**Comment by Domi04151309** [comment]
I can take a look at it but it might take some months because I have to do a lot for school recently.

**Comment by adolfintel** [comment]
Ok, I'll leave the issue open for a few days in case someone else has this problem

**Comment by mijorus** [comment]
The app is sending 500+ notifications a day, I guess this is why Android marks it as "battery drain"
