### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by kolaente** [adolfintel/OpenPods#9]
Hey there, is there a reason this app needs permission to access my location?

**Comment by adolfintel** [comment]
Yes, on Android you need location access to use Bluetooth LE. I know, it doesn't make sense.

**Comment by kolaente** [comment]
I see, thanks for the fast response!

**Comment by SebiderSushi** [comment]
@kolaente In case you still want any more technical insight:

This does not only apply if an Android application wants to access Bluetooth but also if it tries querying Wi-Fi networks.
The reasoning behind this is that the current location can be deduced from surrounding networks and, apparently, surrounding bluetooth devices. All you need is access to a large database mapping IDs of Bluetooth or Wi-Fi devices to places where their signal can be received. This is how network based location services work, like the one built into Google Play Services or offered on Apple iOS devices or the one offered by Mozilla. And it's why in the case of Android it has been decided that giving an application access to Bluetooth and Wi-Fi Scanning on your device is equivalent to giving it access to your location and should hence be communicated as such towards the user.
