### ISSUE TITLE
Warn users of MIUI & EMUI

### ISSUE THREAD

**Issue by Electric1447** [adolfintel/OpenPods#90]
We should inform MIUI & EMUI users of possible incompatibilities with the main branch of OpenPods.

We'll do this by detecting `Build.MANUFACTURER` and acting accordingy

**Comment by adolfintel** [comment]
I think MIUI exposes an API to detect it, I remember reading about it years ago

**Comment by Electric1447** [comment]
We could also do that in addition

**Comment by adolfintel** [comment]
It's probably better because Build.MANUFACTURER would only tell you that it's a Huawei device. MIUI supports other brands too, and Huawei phones may have a custom ROM on it

**Comment by Electric1447** [comment]
We could display the notification for MIUI & EMUI and say in it about custom roms.
Also it would just be a warning, it wouldn't prevent users from using the app if they desire

**Comment by adolfintel** [comment]
Yes, it should just be a warning when the user launches the app the first time

**Comment by adolfintel** [comment]
Do you want to do it or should I do it? I have time today

**Comment by Electric1447** [comment]
Not at home for couple days, do it yourself and I'll see if there is anything to change/fix

**Comment by adolfintel** [comment]
Done. I put it in MainActivity, it's shown only once when the app is first started. Feel free to improve and add the Hebrew translation.

**Comment by Electric1447** [comment]
Made slight improvement in #91 so dismissing the alertdialog would make not show again (previously we needed to click the neutral button)

Also: Hebrew translation

**Comment by Electric1447** [comment]
Now we need to implement a warning for EMUI

**Comment by Electric1447** [comment]
I might do it later

**Comment by adolfintel** [comment]
This should work for EMUI as well, since it's a fork. I have no way to test it though.
