### ISSUE TITLE
PodService beacon payload

### ISSUE THREAD

**Issue by pantonis** [adolfintel/OpenPods#96]
I have run your example and I get invalid data as you describe them. 
This is the hex string that I get ```07-19-01-0E-20-55-AA-B5-31-00-04-24-04-AD-A1-28-5C-C6-94-81-2D-32-6E-4A-B0-51-B7```
Converting these values give incorrect data compared to your implementaion in the PodService. e.g ```7th char is B5 which gives symbol µ``` , ```12th and 13th chars give 04,24 which give EOT and Dollar sign```

Can you assist please?

**Comment by adolfintel** [comment]
When I said char I meant it as in hexadecimal character (4 bits), not ASCII character.
In your case, the 12th and 13th characters are A,A (10, 10 in decimal) so your airpods are fully charged.

**Comment by pantonis** [comment]
@adolfintel Thank you.
