### ISSUE TITLE
Feature Request: Create a windows compatible app?

### ISSUE THREAD

**Issue by InfinityZ25** [adolfintel/OpenPods#98]
This is a really cool project and creating a similar version that runs on windows 10, and maybe even linux, would be pretty cool.

**Comment by Domi04151309** [comment]
Take a look at this.
https://github.com/tzY15368/WinPods

**Comment by adolfintel** [comment]
Nice application, the readme says it was inspired by OpenPods :)
I don't see anything like it on linux though, might be an idea for a future project.

**Comment by niiiksh** [comment]
> This is a really cool project and creating a similar version that runs on windows 10, and maybe even linux, would be pretty cool.

I have a Linux project tested on Debian 8 Jessie. Need to clean up the code and upload on Github

**Comment by niiiksh** [comment]
I'm also writing UWP app for windows 10 inspired by OpenPods :) 
It will be available in Microsoft store occasionally

**Comment by adolfintel** [comment]
@niiiksh if you could distribute it as an appx package to download (or a regular exe) that would be great. A lot of people don't want to use the microsoft store

**Comment by niiiksh** [comment]
@adolfintel I know MS store is not a popular thing, it seems like MS abandoned it today. I'm looking for the best ways to distribute the app. I want to reach people on Windows 10 with a free app and store seems to be the best solution for now
Of course, also I can distribute the appx through a website but how a lot of people will find it?
I would appreciate If you share any promising ideas on distribution

**Comment by adolfintel** [comment]
Personally, I would do both: put it on the store for visibility, use the github releases to distribute appx files for manual installation, put it on your website if you have one, and if possible, port it to Win32,

**Comment by niiiksh** [comment]
@adolfintel the reason I choose UWP is a design that matches the Windows today
I hope MS will bring all the UWP APIs and design language to Win32/WPF soon

**Comment by niiiksh** [comment]
> This is a really cool project and creating a similar version that runs on windows 10, and maybe even linux, would be pretty cool.

I've pushed Linux extension for GNOME (tested on 3.14.1 debian 8 and should work with newer) but it needs to be improved. Basically it works 
https://github.com/niiiksh/airpods_extension/
