### ISSUE TITLE
Huawei Device Not Working

### ISSUE THREAD

**Issue by enes-sakut** [adolfintel/OpenPods#99]
Hi,

I run this app on my Android device  and my air pods battery level is not display. And this UUID's does not exist 2.generation air pods. 
`74ec2172-0bad-4d01-8f77-997b2be0722a`
Is there a battery service UUID this project? How can I display current battery status?

Thanks

**Comment by adolfintel** [comment]
We know, it's a MIUI problem with power saving, we added a warning in the new version.

The older version 1.3 might work though.
